import 'package:otp/otp.dart';

/// RFC 6238 TOTP generation/verification for the authenticator-app unlock
/// method (GitHub #104). A thin wrapper around the `otp` package that pins
/// down the choices that make codes match what Google Authenticator/Authy/
/// Microsoft Authenticator etc. actually compute — see the design doc at
/// `docs/superpowers/specs/2026-09-06-unlock-method-choice-design.md`.
class Totp {
  const Totp._();

  static const _algorithm = Algorithm.SHA1;
  static const _stepSeconds = 30;

  /// A fresh secret — 10 random bytes, base32-encoded. The same size Google
  /// Authenticator's own setup generates.
  static String generateSecret() => OTP.randomSecret();

  /// The `otpauth://` URI a QR code encodes for provisioning. Deliberately
  /// carries no `algorithm` param: mainstream authenticator apps ignore it
  /// and always compute SHA1 regardless, so omitting it can't cause a
  /// mismatch with an app that doesn't honor it.
  static String provisioningUri(String secret, {String label = 'Net Worth'}) {
    final query = {
      'secret': secret,
      'issuer': 'Net Worth',
      'digits': '6',
      'period': '$_stepSeconds',
    }.entries.map((e) => '${e.key}=${Uri.encodeComponent(e.value)}').join('&');
    return 'otpauth://totp/${Uri.encodeComponent(label)}?$query';
  }

  /// The 6-digit code valid at [time] (defaults to now) — used to confirm
  /// setup and, in tests, to verify against a fixed instant rather than the
  /// real clock.
  static String codeAt(String secret, {DateTime? time}) =>
      OTP.generateTOTPCodeString(
        secret,
        (time ?? DateTime.now()).millisecondsSinceEpoch,
        algorithm: _algorithm,
        isGoogle: true,
      );

  /// Accepts the current 30s step and one step either side, so a clock a
  /// little ahead/behind — or a code typed right at a step boundary — still
  /// verifies. A malformed secret (never expected once one is generated by
  /// [generateSecret]) fails closed rather than throwing.
  static bool verify(String secret, String code, {DateTime? now}) {
    final at = now ?? DateTime.now();
    try {
      for (final offsetSeconds in [0, -_stepSeconds, _stepSeconds]) {
        final candidate = codeAt(
          secret,
          time: at.add(Duration(seconds: offsetSeconds)),
        );
        if (OTP.constantTimeVerification(candidate, code)) return true;
      }
    } on FormatException {
      return false;
    }
    return false;
  }
}
